- name: Download Calico VXLAN manifest
  get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/calico-vxlan.yaml
    dest: /etc/kubernetes/calico.yaml
    mode: "0644"
    force: yes

- name: Configure Pod CIDR
  replace:
    path: /etc/kubernetes/calico.yaml
    regexp: '(\s+)# - name: CALICO_IPV4POOL_CIDR\n\s+#   value: "192.168.0.0/16"'
    replace: '\1- name: CALICO_IPV4POOL_CIDR\n\1  value: "10.244.0.0/16"'

- name: Configure VXLAN Mode
  replace:
    path: /etc/kubernetes/calico.yaml
    regexp: '(\s+)- name: CALICO_IPV4POOL_VXLAN\n\s+value: "CrossSubnet"'
    replace: '\1- name: CALICO_IPV4POOL_VXLAN\n\1  value: "Always"'

- name: Apply Calico VXLAN manifest
  command: kubectl apply -f /etc/kubernetes/calico.yaml
  register: calico_apply
  retries: 6
  delay: 10
  until: calico_apply.rc == 0

- name: Wait for Calico pods to be ready
  command: kubectl wait --for=condition=ready pod -l k8s-app=calico-node -n kube-system --timeout=300s
  register: wait_calico
  retries: 10
  delay: 30
  until: wait_calico.rc == 0

- name: Wait for cluster network functionality
  command: kubectl get nodes -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}'
  register: nodes_ready
  retries: 20
  delay: 15
  until: nodes_ready.stdout | regex_search('^True(\s+True)*$')