- name: Download Calico VXLAN manifest
  get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/calico-vxlan.yaml
    dest: /etc/kubernetes/calico.yaml
    mode: "0644"
    force: yes

- name: Configure Pod CIDR
  replace:
    path: /etc/kubernetes/calico.yaml
    regexp: '(\s+)# - name: CALICO_IPV4POOL_CIDR\n\s+#   value: "192.168.0.0/16"'
    replace: '\1- name: CALICO_IPV4POOL_CIDR\n\1  value: "10.244.0.0/16"'

- name: Configure VXLAN Mode
  replace:
    path: /etc/kubernetes/calico.yaml
    regexp: '(\s+)- name: CALICO_IPV4POOL_VXLAN\n\s+value: "CrossSubnet"'
    replace: '\1- name: CALICO_IPV4POOL_VXLAN\n\1  value: "Always"'

- name: Reduce Calico pod startup delay
  replace:
    path: /etc/kubernetes/calico.yaml
    regexp: 'name: CALICO_NODE_READY_TIMEOUT\n\s+value: "60"'
    replace: 'name: CALICO_NODE_READY_TIMEOUT\n  value: "15"'

- name: Apply Calico VXLAN manifest
  command: kubectl apply -f /etc/kubernetes/calico.yaml
  register: calico_apply
  retries: 6
  delay: 10
  until: calico_apply.rc == 0

- name: Wait for Calico pods to be ready (skip offline nodes)
  shell: |
    for pod in $(kubectl get pods -n kube-system -l k8s-app=calico-node -o jsonpath='{.items[*].metadata.name}'); do
      kubectl wait pod/$pod -n kube-system --for=condition=Ready --timeout=15s || true
    done
  register: calico_wait
  retries: 6
  delay: 5
  until: calico_wait.rc == 0
